### ISSUE TITLE
add option to hide ui

### ISSUE THREAD

**Issue by xrva** [yiruzu/cloud-deathscreen#2]
add option to hide ui/show ui please because i use revive script which when you target on it and press on it, it puts you to hospital for revival, and also add option to use mouse when ui is hidden.

**Comment by yiruzu** [comment]
the script is open source, thats like 2-3 lines you gotta remove thats it

**Comment by xrva** [comment]
so what do i exactly remove

**Comment by yiruzu** [comment]
look at the ToggleUI function in the client and remove all the logic inside of it
